/**
 * Export helpers for bug-bounty reports — Markdown (HackerOne-friendly) and JSON.
 */

import type { Severity } from "./cvss";

export type FindingExport = {
  id: string;
  title: string;
  severity: Severity;
  category: string;
  cvssVector?: string;
  cvssScore?: number;
  affectedUrl?: string;
  description: string;
  reproductionSteps: string[];
  remediation?: string;
  evidenceFrameIndices: number[];
  request?: string;
  response?: string;
  reportedAt: string;
};

export type EngagementExport = {
  name: string;
  type: string;            // bug_bounty | pentest | ctf | personal
  inScope: string[];
  outOfScope: string[];
  intensity: string;       // passive | active | exploitation
  authorized: boolean;
  task: string;
  startedAt: string;
  endedAt?: string;
};

const SEVERITY_ORDER: Record<Severity, number> = { Critical: 0, High: 1, Medium: 2, Low: 3, Info: 4 };

export function sortFindingsBySeverity(findings: FindingExport[]): FindingExport[] {
  return [...findings].sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
}

export function findingsToMarkdown(engagement: EngagementExport, findings: FindingExport[], summary: string): string {
  const sorted = sortFindingsBySeverity(findings);
  const sevCounts = sorted.reduce<Record<string, number>>((acc, f) => {
    acc[f.severity] = (acc[f.severity] || 0) + 1;
    return acc;
  }, {});

  const lines: string[] = [];
  lines.push(`# Bug Bounty Report — ${engagement.name}`);
  lines.push("");
  lines.push(`**Engagement type:** ${engagement.type}  `);
  lines.push(`**Test intensity:** ${engagement.intensity}  `);
  lines.push(`**Authorized:** ${engagement.authorized ? "✅ Yes" : "❌ No"}  `);
  lines.push(`**Started:** ${engagement.startedAt}  `);
  if (engagement.endedAt) lines.push(`**Ended:** ${engagement.endedAt}  `);
  lines.push("");
  lines.push(`## Scope`);
  lines.push(`**In-scope:**`);
  engagement.inScope.forEach((s) => lines.push(`- \`${s}\``));
  if (engagement.outOfScope.length) {
    lines.push(`**Out-of-scope:**`);
    engagement.outOfScope.forEach((s) => lines.push(`- \`${s}\``));
  }
  lines.push("");
  lines.push(`## Executive Summary`);
  lines.push(summary || "_No summary._");
  lines.push("");
  lines.push(`## Findings Overview`);
  lines.push(`Total findings: **${sorted.length}**  `);
  Object.entries(sevCounts).forEach(([sev, n]) => lines.push(`- ${sev}: ${n}`));
  lines.push("");

  sorted.forEach((f, i) => {
    lines.push(`---`);
    lines.push(`## Finding ${i + 1}: ${f.title}`);
    lines.push(`**Severity:** ${f.severity}${f.cvssScore ? ` (CVSS ${f.cvssScore})` : ""}  `);
    if (f.cvssVector) lines.push(`**CVSS Vector:** \`${f.cvssVector}\`  `);
    lines.push(`**Category:** ${f.category}  `);
    if (f.affectedUrl) lines.push(`**Affected URL:** ${f.affectedUrl}  `);
    lines.push("");
    lines.push(`### Description`);
    lines.push(f.description);
    lines.push("");
    if (f.reproductionSteps.length) {
      lines.push(`### Steps to Reproduce`);
      f.reproductionSteps.forEach((s, j) => lines.push(`${j + 1}. ${s}`));
      lines.push("");
    }
    if (f.request) {
      lines.push(`### Request`);
      lines.push("```http");
      lines.push(f.request);
      lines.push("```");
      lines.push("");
    }
    if (f.response) {
      lines.push(`### Response`);
      lines.push("```http");
      lines.push(f.response);
      lines.push("```");
      lines.push("");
    }
    if (f.remediation) {
      lines.push(`### Remediation`);
      lines.push(f.remediation);
      lines.push("");
    }
  });

  lines.push(`---`);
  lines.push(`_Generated by Emma Computer-Use Agent · ${new Date().toISOString()}_`);
  return lines.join("\n");
}

export function findingsToJson(engagement: EngagementExport, findings: FindingExport[], summary: string): string {
  return JSON.stringify({
    engagement,
    summary,
    findings: sortFindingsBySeverity(findings),
    generatedAt: new Date().toISOString(),
    schema: "emma.bugbounty.v1",
  }, null, 2);
}

export function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function sha256Hex(data: string): Promise<string> {
  const bytes = new TextEncoder().encode(data);
  const buf = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
