import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Atom, ArrowLeft, Sparkles, Loader2 } from "lucide-react";
import { toast } from "sonner";

interface Invention {
  id: string;
  name: string;
  domain: string | null;
  hypothesis: string | null;
  mechanism: string | null;
  equations: string | null;
  predictions: string | null;
  applications: string | null;
  novelty_score: number | null;
  source: string | null;
  created_at: string;
}

const FN_URL = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/emma-physics-invent`;
const ANON = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export default function PhysicsInventions() {
  const [items, setItems] = useState<Invention[]>([]);
  const [loading, setLoading] = useState(true);
  const [inventing, setInventing] = useState(false);
  const [open, setOpen] = useState<string | null>(null);
  const [prompt, setPrompt] = useState("");

  const load = async () => {
    setLoading(true);
    try {
      const r = await fetch(FN_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${ANON}`, apikey: ANON },
        body: JSON.stringify({ action: "list" }),
      });
      const j = await r.json();
      setItems(j.inventions || []);
    } catch (e) {
      toast.error("Failed to load inventions");
    } finally {
      setLoading(false);
    }
  };

  const inventNow = async () => {
    setInventing(true);
    try {
      const r = await fetch(FN_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${ANON}`, apikey: ANON },
        body: JSON.stringify({ manual: true, count: 1, prompt: prompt.trim() || undefined }),
      });
      const j = await r.json();
      if (j.created?.length) {
        toast.success(`Invented: ${j.created[0].name}`);
        load();
      } else {
        toast.error(j.error || "No invention created");
      }
    } catch {
      toast.error("Invention failed");
    } finally {
      setInventing(false);
    }
  };

  useEffect(() => { load(); }, []);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/50 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link to="/"><Button variant="ghost" size="icon"><ArrowLeft className="h-4 w-4" /></Button></Link>
          <Atom className="h-5 w-5 text-primary" />
          <div>
            <h1 className="text-lg font-semibold">Physics Inventions</h1>
            <p className="text-xs text-muted-foreground">Autonomously generated by Emma</p>
          </div>
        </div>
        <Button onClick={inventNow} disabled={inventing} size="sm" className="gap-2">
          {inventing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
          Invent now
        </Button>
      </header>

      <main className="max-w-5xl mx-auto p-6 space-y-3">
        {loading ? (
          <div className="text-center py-12 text-muted-foreground">Loading…</div>
        ) : items.length === 0 ? (
          <Card className="p-12 text-center text-muted-foreground">
            No inventions yet. Click "Invent now" or wait for the cron to fire.
          </Card>
        ) : (
          items.map((it) => (
            <Card key={it.id} className="p-4 hover:border-primary/50 transition-colors cursor-pointer"
                  onClick={() => setOpen(open === it.id ? null : it.id)}>
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <h3 className="font-semibold truncate">{it.name}</h3>
                  <div className="flex items-center gap-2 mt-1 flex-wrap">
                    {it.domain && <Badge variant="secondary" className="text-xs">{it.domain}</Badge>}
                    {it.novelty_score != null && (
                      <Badge variant="outline" className="text-xs">novelty {Number(it.novelty_score).toFixed(1)}/10</Badge>
                    )}
                    <span className="text-xs text-muted-foreground">
                      {new Date(it.created_at).toLocaleString()} · {it.source}
                    </span>
                  </div>
                </div>
              </div>
              {open === it.id && (
                <div className="mt-4 space-y-3 text-sm border-t border-border/50 pt-4">
                  {it.hypothesis && <Section label="Hypothesis" body={it.hypothesis} />}
                  {it.mechanism && <Section label="Mechanism" body={it.mechanism} />}
                  {it.equations && <Section label="Equations" body={it.equations} mono />}
                  {it.predictions && <Section label="Predictions" body={it.predictions} />}
                  {it.applications && <Section label="Applications" body={it.applications} />}
                </div>
              )}
            </Card>
          ))
        )}
      </main>
    </div>
  );
}

function Section({ label, body, mono }: { label: string; body: string; mono?: boolean }) {
  return (
    <div>
      <div className="text-xs uppercase tracking-wide text-muted-foreground mb-1">{label}</div>
      <div className={mono ? "font-mono text-xs whitespace-pre-wrap" : "whitespace-pre-wrap"}>{body}</div>
    </div>
  );
}
