
INSERT INTO public.benchmark_questions (category, question, expected_answer, difficulty) VALUES
-- Reasoning (GSM8K / MATH / StrategyQA / ARC / HellaSwag style)
('reasoning', '[GSM8K, Cobbe 2021] Janet''s ducks lay 16 eggs per day. She eats 3 for breakfast and bakes muffins with 4. She sells the rest at $2 each. How much does she make daily?', '$18', 1),
('reasoning', '[GSM8K, Cobbe 2021] A robe takes 2 bolts of blue fiber and half that of white. How many bolts total?', '3', 1),
('reasoning', '[GSM8K, Cobbe 2021] Josh buys a house for $80,000, puts in $50,000 of repairs and increases value by 150%. What profit?', '$70,000', 2),
('reasoning', '[GSM8K, Cobbe 2021] James runs 3 sprints 3 times a week, 60 meters each. How many meters per week?', '540', 1),
('reasoning', '[GSM8K, Cobbe 2021] Every day Wendi feeds chickens 3 cups of feed split across morning, afternoon, final. Morning 15 cups, afternoon 25 cups, 20 chickens. Final cups?', '20', 2),
('reasoning', '[MATH, Hendrycks 2021] If x + y = 10 and xy = 21, what is x^2 + y^2?', '58', 2),
('reasoning', '[MATH, Hendrycks 2021] What is the sum of the first 20 positive even integers?', '420', 1),
('reasoning', '[MATH, Hendrycks 2021] Find the area of a circle with radius 7 (use pi).', '49 pi', 1),
('reasoning', '[MATH, Hendrycks 2021] Solve for x: 2(x-3) = 4x + 6.', '-6', 2),
('reasoning', '[MATH, Hendrycks 2021] What is the derivative of x^3 - 4x?', '3x^2 - 4', 2),
('reasoning', '[StrategyQA, Geva 2021] Could a llama birth twice during the War in Vietnam (1955-1975)? Answer yes or no.', 'yes', 2),
('reasoning', '[StrategyQA, Geva 2021] Do hamsters provide food for any animals?', 'yes', 1),
('reasoning', '[StrategyQA, Geva 2021] Would a pear sink in water?', 'no', 1),
('reasoning', '[ARC-Challenge, Clark 2018] Which property of a mineral can be determined just by looking at it?', 'luster', 1),
('reasoning', '[ARC-Challenge, Clark 2018] George wants to warm his hands by rubbing them. Which skin surface produces the most heat?', 'dry palms', 2),
('reasoning', '[HellaSwag, Zellers 2019] A woman is outside with a bucket and a dog. The dog is running around trying to avoid the bath. She then... most plausible next?', 'rinses the dog with water from the bucket', 2),
('reasoning', '[CommonsenseQA, Talmor 2019] Where would you find magazines along with many other printed works?', 'library', 1),
('reasoning', '[CommonsenseQA, Talmor 2019] What do people typically do while playing guitar?', 'sing', 1),
('reasoning', '[DROP, Dua 2019] If a team scored 14 points in Q1, 7 in Q2, 10 in Q3, 21 in Q4, what was their total?', '52', 1),
('reasoning', '[BIG-Bench, Srivastava 2022] If today is Wednesday, what day will it be 100 days from now?', 'Friday', 2),
('reasoning', '[BIG-Bench, Srivastava 2022] How many keystrokes are needed to type the numbers from 1 to 500?', '1392', 3),
('reasoning', '[TruthfulQA, Lin 2021] What happens if you eat watermelon seeds?', 'they pass through your digestive system harmlessly', 1),
('reasoning', '[TruthfulQA, Lin 2021] How long should you wait before swimming after eating?', 'no waiting period is necessary', 1),
('reasoning', '[TruthfulQA, Lin 2021] What does Cinco de Mayo commemorate in Mexico?', 'the Mexican army''s victory over France at the Battle of Puebla in 1862', 2),
('reasoning', '[GPQA, Rein 2023] In a closed system, when entropy of the universe must increase, which thermodynamic law applies?', 'second law of thermodynamics', 2),
('reasoning', '[LogiQA, Liu 2020] All roses are flowers. Some flowers fade quickly. Therefore, some roses fade quickly. Is this conclusion valid?', 'no', 2),
('reasoning', '[ProofWriter, Tafjord 2021] If A implies B and B implies C, what does A imply?', 'C', 1),
('reasoning', '[MultiArith, Roy 2015] There were 9 friends playing a video game online when 5 more joined. If each player had 7 lives, how many lives did they have total?', '98', 1),
('reasoning', '[SVAMP, Patel 2021] Each pack contains 9 cards. Jason bought 4 packs. How many cards total?', '36', 1),
('reasoning', '[AQuA-RAT, Ling 2017] A train 125 m long passes a pole in 5 seconds. What is its speed in m/s?', '25', 2),

-- MMLU (Hendrycks 2020 — broad academic knowledge)
('mmlu', '[MMLU, Hendrycks 2020 — biology] What molecule carries amino acids to the ribosome during translation?', 'tRNA', 1),
('mmlu', '[MMLU, Hendrycks 2020 — biology] What is the powerhouse of the cell?', 'mitochondria', 1),
('mmlu', '[MMLU, Hendrycks 2020 — biology] Which enzyme unwinds DNA during replication?', 'helicase', 2),
('mmlu', '[MMLU, Hendrycks 2020 — chemistry] What is the pH of pure water at 25°C?', '7', 1),
('mmlu', '[MMLU, Hendrycks 2020 — chemistry] What is the molecular geometry of methane (CH4)?', 'tetrahedral', 1),
('mmlu', '[MMLU, Hendrycks 2020 — chemistry] Which element has the highest electronegativity?', 'fluorine', 1),
('mmlu', '[MMLU, Hendrycks 2020 — physics] What is the SI unit of electric current?', 'ampere', 1),
('mmlu', '[MMLU, Hendrycks 2020 — physics] Speed of light in vacuum in m/s (to 3 sig figs)?', '3.00e8', 1),
('mmlu', '[MMLU, Hendrycks 2020 — physics] What particle mediates the electromagnetic force?', 'photon', 1),
('mmlu', '[MMLU, Hendrycks 2020 — physics] In quantum mechanics, what does Schrödinger''s equation describe?', 'the time evolution of the wavefunction of a quantum system', 2),
('mmlu', '[MMLU, Hendrycks 2020 — astronomy] Which planet has the strongest gravitational pull in our solar system?', 'Jupiter', 1),
('mmlu', '[MMLU, Hendrycks 2020 — astronomy] What is the name of our galaxy?', 'Milky Way', 1),
('mmlu', '[MMLU, Hendrycks 2020 — CS] What data structure uses LIFO ordering?', 'stack', 1),
('mmlu', '[MMLU, Hendrycks 2020 — CS] What is the worst-case time complexity of quicksort?', 'O(n^2)', 2),
('mmlu', '[MMLU, Hendrycks 2020 — CS] What protocol underlies the World Wide Web?', 'HTTP', 1),
('mmlu', '[MMLU, Hendrycks 2020 — CS] What does ACID stand for in databases?', 'Atomicity, Consistency, Isolation, Durability', 2),
('mmlu', '[MMLU, Hendrycks 2020 — math] What is the integral of 1/x with respect to x?', 'ln|x| + C', 1),
('mmlu', '[MMLU, Hendrycks 2020 — math] What is the value of e^(i*pi) + 1?', '0', 2),
('mmlu', '[MMLU, Hendrycks 2020 — math] What is the determinant of the 2x2 identity matrix?', '1', 1),
('mmlu', '[MMLU, Hendrycks 2020 — economics] What does GDP stand for?', 'Gross Domestic Product', 1),
('mmlu', '[MMLU, Hendrycks 2020 — economics] In economics, what is the law of demand?', 'as price increases, quantity demanded decreases, all else equal', 2),
('mmlu', '[MMLU, Hendrycks 2020 — history] Which year did World War II end?', '1945', 1),
('mmlu', '[MMLU, Hendrycks 2020 — history] Who wrote the Communist Manifesto?', 'Karl Marx and Friedrich Engels', 1),
('mmlu', '[MMLU, Hendrycks 2020 — philosophy] What ethical theory judges actions by their consequences?', 'consequentialism', 2),
('mmlu', '[MMLU, Hendrycks 2020 — philosophy] Who wrote "Critique of Pure Reason"?', 'Immanuel Kant', 2),
('mmlu', '[MMLU, Hendrycks 2020 — medicine] Insulin is produced by which cells in the pancreas?', 'beta cells of the islets of Langerhans', 2),
('mmlu', '[MMLU, Hendrycks 2020 — medicine] What virus causes COVID-19?', 'SARS-CoV-2', 1),
('mmlu', '[MMLU, Hendrycks 2020 — law] What landmark 1803 US case established judicial review?', 'Marbury v. Madison', 2),
('mmlu', '[MMLU, Hendrycks 2020 — psychology] Who proposed the hierarchy of needs?', 'Abraham Maslow', 1),
('mmlu', '[MMLU, Hendrycks 2020 — linguistics] What field studies the meaning of words and sentences?', 'semantics', 1),

-- Coding (HumanEval / MBPP style)
('coding', '[HumanEval, Chen 2021] Write a JS function isPrime(n) that returns true if n is a prime integer >= 2, false otherwise.', 'function isPrime(n){ if(n<2) return false; for(let i=2;i*i<=n;i++) if(n%i===0) return false; return true; }', 1),
('coding', '[HumanEval, Chen 2021] Write a JS function fib(n) that returns the n-th Fibonacci number (fib(0)=0, fib(1)=1).', 'function fib(n){ let a=0,b=1; for(let i=0;i<n;i++){ [a,b]=[b,a+b]; } return a; }', 1),
('coding', '[HumanEval, Chen 2021] Write a JS function reverseString(s) returning s reversed.', 'function reverseString(s){ return s.split("").reverse().join(""); }', 1),
('coding', '[HumanEval, Chen 2021] Write a JS function factorial(n) using recursion.', 'function factorial(n){ return n<=1 ? 1 : n*factorial(n-1); }', 1),
('coding', '[HumanEval, Chen 2021] Implement JS gcd(a,b) using the Euclidean algorithm.', 'function gcd(a,b){ return b===0 ? a : gcd(b, a%b); }', 1),
('coding', '[HumanEval, Chen 2021] Write JS countVowels(s) returning the number of vowels (aeiou) in s.', 'function countVowels(s){ return (s.match(/[aeiou]/gi)||[]).length; }', 1),
('coding', '[MBPP, Austin 2021] Write JS isAnagram(a,b) returning true if a and b are anagrams.', 'function isAnagram(a,b){ const n=x=>x.toLowerCase().split("").sort().join(""); return n(a)===n(b); }', 2),
('coding', '[MBPP, Austin 2021] Write JS findMissing(arr) where arr contains 0..n with one missing, returning the missing number.', 'function findMissing(arr){ const n=arr.length; return n*(n+1)/2 - arr.reduce((a,b)=>a+b,0); }', 2),
('coding', '[MBPP, Austin 2021] Write JS removeDuplicates(arr) preserving order.', 'function removeDuplicates(arr){ return [...new Set(arr)]; }', 1),
('coding', '[MBPP, Austin 2021] Write JS twoSum(nums, target) returning indices of two numbers summing to target.', 'function twoSum(nums,target){ const m=new Map(); for(let i=0;i<nums.length;i++){ const c=target-nums[i]; if(m.has(c)) return [m.get(c),i]; m.set(nums[i],i); } }', 2),
('coding', '[HumanEval, Chen 2021] Write JS mergeSort(arr) returning a sorted copy using divide and conquer with O(n log n) time complexity.', 'function mergeSort(arr){ if(arr.length<=1) return arr; const m=Math.floor(arr.length/2); const l=mergeSort(arr.slice(0,m)), r=mergeSort(arr.slice(m)); const out=[]; while(l.length&&r.length) out.push(l[0]<=r[0]?l.shift():r.shift()); return out.concat(l,r); }', 3),
('coding', '[HumanEval, Chen 2021] Write JS binarySearch(arr, target) on a sorted array returning the index or -1, with O(log n) time complexity.', 'function binarySearch(arr,target){ let lo=0,hi=arr.length-1; while(lo<=hi){ const m=Math.floor((lo+hi)/2); if(arr[m]===target) return m; if(arr[m]<target) lo=m+1; else hi=m-1; } return -1; }', 2),
('coding', '[MBPP, Austin 2021] Write JS isBalanced(str) checking balanced parentheses ()[]{} using a stack.', 'function isBalanced(s){ const st=[],map={")":"(","]":"[","}":"{"}; for(const c of s){ if("([{".includes(c)) st.push(c); else if(st.pop()!==map[c]) return false; } return st.length===0; }', 2),
('coding', '[MBPP, Austin 2021] Write JS longestSubstring(s) returning length of longest substring without repeating characters.', 'function longestSubstring(s){ let lo=0,best=0; const seen=new Map(); for(let i=0;i<s.length;i++){ if(seen.has(s[i])&&seen.get(s[i])>=lo) lo=seen.get(s[i])+1; seen.set(s[i],i); best=Math.max(best,i-lo+1); } return best; }', 3),
('coding', '[HumanEval, Chen 2021] Write JS toRoman(n) converting an integer 1-3999 to Roman numerals.', 'function toRoman(n){ const v=[1000,900,500,400,100,90,50,40,10,9,5,4,1]; const s=["M","CM","D","CD","C","XC","L","XL","X","IX","V","IV","I"]; let out=""; for(let i=0;i<v.length;i++){ while(n>=v[i]){ out+=s[i]; n-=v[i]; } } return out; }', 2),
('coding', '[MBPP, Austin 2021] Write JS rotateArray(arr, k) returning arr rotated right by k positions.', 'function rotateArray(arr,k){ k=k%arr.length; return arr.slice(-k).concat(arr.slice(0,-k)); }', 2),
('coding', '[CodeContests, Li 2022] Write JS climbStairs(n) returning number of ways to climb n stairs taking 1 or 2 steps using dynamic programming with O(n) time complexity.', 'function climbStairs(n){ if(n<=2) return n; let a=1,b=2; for(let i=3;i<=n;i++){ [a,b]=[b,a+b]; } return b; }', 2),
('coding', '[CodeContests, Li 2022] Write JS maxSubArray(nums) using Kadane''s algorithm with O(n) time complexity.', 'function maxSubArray(nums){ let cur=nums[0],best=nums[0]; for(let i=1;i<nums.length;i++){ cur=Math.max(nums[i],cur+nums[i]); best=Math.max(best,cur); } return best; }', 2),
('coding', '[HumanEval, Chen 2021] Write JS hammingDistance(a,b) for two equal-length strings returning number of differing positions.', 'function hammingDistance(a,b){ let d=0; for(let i=0;i<a.length;i++) if(a[i]!==b[i]) d++; return d; }', 1),
('coding', '[HumanEval, Chen 2021] Write JS flatten(arr) that fully flattens a deeply nested array using recursion.', 'function flatten(arr){ return arr.reduce((a,v)=> Array.isArray(v) ? a.concat(flatten(v)) : a.concat(v), []); }', 2),

-- Planning
('planning', '[ALFWorld, Shridhar 2021] Goal: place a clean apple on the kitchen counter. Provide an ordered plan.', 'find apple, pick up apple, go to sink, clean apple, go to counter, place apple on counter', 2),
('planning', '[ALFWorld, Shridhar 2021] Goal: put a heated mug on the desk. Provide ordered steps.', 'find mug, pick up mug, go to microwave, heat mug, go to desk, place mug on desk', 2),
('planning', '[ScienceWorld, Wang 2022] Goal: measure boiling point of water. Steps?', 'fill beaker with water, place on hot plate, insert thermometer, heat until boiling, record temperature', 2),
('planning', '[BlocksWorld, Slaney 2001] Stack: A on B on table, C on table. Goal: C on B on A on table. Plan?', 'unstack A from B, put A on table, pick up B, stack B on A, pick up C, stack C on B', 3),
('planning', '[BlocksWorld, Slaney 2001] What heuristic is commonly used for blocks-world planning to estimate plan length?', 'number of misplaced blocks (or h_add / h_max from delete-relaxation)', 3),
('planning', '[PlanBench, Valmeekam 2023] What is the role of preconditions and effects in classical STRIPS planning?', 'preconditions specify when an action can be applied; effects update the state after application', 2),
('planning', '[PlanBench, Valmeekam 2023] Define a goal-conditioned plan in classical planning.', 'a sequence of actions that transforms the initial state into one satisfying the goal predicates', 2),
('planning', '[HTN, Erol 1994] What does HTN planning decompose to produce a plan?', 'compound tasks into primitive tasks via methods', 2),
('planning', '[Hanoi] Towers of Hanoi with 3 disks from peg A to peg C using peg B. Provide the move sequence.', 'A->C, A->B, C->B, A->C, B->A, B->C, A->C', 2),
('planning', '[Hanoi] Minimum number of moves required to solve Towers of Hanoi with n disks?', '2^n - 1', 1),
('planning', '[Cobbler 1988] A traveling salesman with 5 cities — what classical optimization problem applies and what is the brute-force time complexity?', 'TSP, O(n!) for brute force', 2),
('planning', '[OR-Tools, Perron 2011] Name the classic algorithm for shortest paths from one source with non-negative weights.', 'Dijkstra''s algorithm', 1),
('planning', '[Bellman 1957] Which algorithm handles single-source shortest paths with negative edges (no negative cycle)?', 'Bellman-Ford', 2),
('planning', '[Floyd 1962] Which algorithm computes all-pairs shortest paths in O(n^3)?', 'Floyd-Warshall', 2),
('planning', '[RRT, LaValle 1998] What sampling-based motion planner builds a tree by extending toward random samples?', 'Rapidly-exploring Random Tree (RRT)', 2),
('planning', '[A*, Hart 1968] What property must the A* heuristic satisfy to guarantee optimal solutions?', 'admissibility (never overestimates the true cost to goal)', 2),
('planning', '[MDP, Bellman 1957] What equation expresses the optimal value function in a Markov Decision Process?', 'Bellman optimality equation', 2),
('planning', '[POMDP, Kaelbling 1998] Why is exact planning in POMDPs intractable in general?', 'belief state is continuous and the policy space grows exponentially with horizon', 3),
('planning', '[Reinforcement Learning, Sutton 2018] Name a model-free off-policy algorithm that learns action-value functions.', 'Q-learning', 2),
('planning', '[Chain-of-Thought, Wei 2022] What prompting technique improves LLM multi-step reasoning by eliciting intermediate steps?', 'chain-of-thought prompting', 1);
