
ALTER TABLE public.agent_runs
  ADD COLUMN IF NOT EXISTS last_url TEXT,
  ADD COLUMN IF NOT EXISTS tab_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS form_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS restore_count INTEGER NOT NULL DEFAULT 0;
